config/routes.rb
Rails.application.routes.draw do
  namespace :v1, defaults: { format: 'json' } do
    post 'auth/login', to: 'authentication#authenticate'
    post 'signup', to: 'users#create'

    resources 'restaurants', only: [ :index, :create, :destroy]

    resources :reservations

  end
  get '*page', to: 'static#index', constraints: ->(req) do
    !req.xhr? && req.format.html?
  end
  root 'static#index';
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :resturant

  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/models/resturant.rb
class Resturant < ApplicationRecord
  has_many :reservations, dependent: :destroy

  validates :name, presence: true
  validates :image, presence: true
  validates :location, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :todos, foreign_key: :created_by

  validates :name, uniqueness: true, length: { in: 2...20 }
  validates :password_digest, length: { minimum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  include ExceptionHandler

  # called before every action on controllers
  before_action :authorize_request
  attr_reader :current_user

  private

  # Check for valid request token and return user
  def authorize_request
    @current_user = (AuthorizeApiRequest.new(request.headers).call)[:user]
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
    skip_before_action :authorize_request

    # return auth token once user is authenticated
    def authenticate
      auth_token =
        AuthenticateUser.new(auth_params[:name], auth_params[:password_digest]).call
      render json: {message: 'Successfully signed up',auth_token: auth_token}, status: 200
    end
  
    private
  
    def auth_params
      params.require(:user).permit(:name, :password_digest)
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  skip_before_action :authorize_request
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorize_request
    
    def create
        @user = User.new(user_params)
        if @user.valid? 
            @user.save
            auth_token = AuthenticateUser.new(@user.name, @user.password_digest).call
            response = { message: Message.account_created, auth_token: auth_token }
            render json: response, status: 200
        else
            render json: {error: @user.errors}, status: 200 
        end
       
    end

    private

    def user_params
        params.require(:user).permit(:name, :password_digest)
    end
end

app/controllers/v1/authentication_controller.rb
class V1::AuthenticationController < ApplicationController
  skip_before_action :authorize_request

  # return auth token once user is authenticated
  def authenticate
    auth_token =
      AuthenticateUser.new(auth_params[:name], auth_params[:password_digest]).call
    render json: { message: 'Successfully signed in', auth_token: auth_token }, status: 200
  end

  private

  def auth_params
    params.require(:user).permit(:name, :password_digest)
  end
end

app/controllers/v1/reservations_controller.rb
class V1::ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[show edit update destroy]

  # GET /reservations or /reservations.json
  def index
    @user = current_user
    @reservations = Reservation.where(user_id: @user.id)
    render json: { reservations: @reservations }, status: 200
  end

  # GET /reservations/1 or /reservations/1.json
  def show; end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(
      user_id: current_user.id,
      resturant_id: params[:resturant_id],
      start_time: params[:start_time],
      end_time: params[:end_time]
    )
    if @reservation.save
      render json: { message: 'Reservation created successfully' }, status: :created
    else
      render json: { errors: @reservation.errors }, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |_format|
      if @reservation.update(reservation_params)
        render json: { message: 'Reservation was successfully updated.' }, status: :ok
      else
        render json: { errors: @reservation.errors }, status: :unprocessable_entity
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy

    render json: { message: 'Reservation deleted successfully' }, status: :ok
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  # def reservation_params
  #   params.require(:reservation).permit(:start_time, :end_time, :resturant_id)
  # end
end

app/controllers/v1/restaurants_controller.rb
class V1::RestaurantsController < ApplicationController
  skip_before_action :authorize_request

  def index
    @restaurants = Resturant.all
    render json: {
      restaurants: @restaurants
    }, status: 200
  end

  def create
    @restaurant = Resturant.new(restaurant_params)

    if @restaurant.save
      render json: { message: 'Restaurant has been created' }, status: 200
    else
      render json: { errors: @restaurant.errors }, status: 422
    end
  end

  def destroy
    Resturant.find(params[:id]).destroy

    render json: { message: 'Restaurant deleted successfully' }, status: :ok
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :rating, :image, :location)
  end
end

app/controllers/v1/users_controller.rb
class V1::UsersController < ApplicationController
  skip_before_action :authorize_request

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      auth_token = AuthenticateUser.new(@user.name, @user.password_digest).call
      response = { message: Message.account_created, auth_token: auth_token }
      render json: response, status: 200
    else
      render json: { error: @user.errors }, status: 200
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password_digest)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeResturant</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th>End time</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.name %></td>
        <td><%= reservation.start_time %></td>
        <td><%= reservation.end_time %></td>
        <td><%= reservation.user_id %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reservation.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @reservation.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @reservation.end_time %>
</p>

<p>
  <strong>User:</strong>
  <%= @reservation.user_id %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>